language: cpp
compiler:
    - gcc
os:
    - linux
    - osx
matrix:
    allow_failures:
        - os: osx
branches:
    only:
        - master
        - mpi
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - bhalla@ncbs.res.in
        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly
cache: apt
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libxml2-dev libbz2-dev
    - sudo apt-get install libhdf5-serial-dev
    - sudo apt-get install python-numpy python-setuptools python-networkx
    - sudo apt-get install make texinfo cmake
    - sudo apt-get install python-suds python-matplotlib
    - sudo apt-get install python-qt4-dev python-qt4-gl python-sip-dev libqt4-dev libopenscenegraph-dev
    - sudo apt-get install doxygen python-sphinx

install:
    - wget ftp://ftp.gnu.org/gnu/gsl/gsl-1.16.tar.gz
    - tar -xzvf gsl-1.16.tar.gz
    - cd gsl-1.16 
    - ./configure --prefix=/usr > /dev/null
    - make > /dev/null
    - sudo make install  > /dev/null
    - cd ..
    - sbmlurl="http://sourceforge.net/projects/sbml/files/libsbml/5.9.0/stable/Linux/64-bit/libSBML-5.9.0-Linux-x64.deb"
    - sudo -E wget "$sbmlurl" -O "libsbml.deb" && sudo -E dpkg -i "libsbml.deb" && sudo -E rm -rf "libsbml.deb"

script:
    - make BUILD=debug USE_NEUROKIT=1 && make clean
    - mkdir -p _build && cd _build && cmake -DDEBUG=ON -DWITH_DOC=ON -DBUILD_MOOGLI=ON .. && make
    - ctest --output-on-failure
