sudo: required
dist: trusty
language: cpp
compiler:
    - gcc
    - clang
os:
    - linux
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - bhalla@ncbs.res.in
        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly
cache: apt

matrix:
    allow_failures:

before_script:
    - sudo apt-get install -qq libxml2-dev libbz2-dev
    - sudo apt-get install -qq libhdf5-serial-dev
    - sudo apt-get install -qq make cmake
    - sudo apt-get install -qq python-pip python-numpy python-matplotlib
    - sudo apt-get install -qq libboost-all-dev

before_install:
    - sbmlurl="http://sourceforge.net/projects/sbml/files/libsbml/5.9.0/stable/Linux/64-bit/libSBML-5.9.0-Linux-x64.deb"
    - wget "$sbmlurl" -O libsbml.deb && sudo dpkg -i libsbml.deb 
    - sudo apt-get install -f
    - /usr/bin/python; /usr/loca/bin/python
    - which python
    - python -c 'import numpy'

install:
    - echo "nothing to do here"

script:
    - sudo ldconfig /usr/lib64
    - mkdir -p _BUILD && cd _BUILD && cmake -DDEBUG=ON ..
    - make -j`nproc` 
    - ctest --output-on-failure
