language: cpp
compiler:
    - clang
os:
    - osx
branches:
    only:
        - master
        - osx
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - bhalla@ncbs.res.in
            - aviralg@ncbs.res.in
            - hrani@ncbs.res.in
        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly
cache: apt

before_script:
    - brew install gsl hdf5 python cmake 
    - brew install homebrew/python/numpy 
    - brew install homebrew/python/matplotlib
    - brew install pyqt
    - brew install openscenegraph

install:
    - echo "nothing to do here"

script:
    - make BUILD=debug USE_NEUROKIT=1 && make clean
    - mkdir -p _build && cd _build && cmake -DDEBUG=ON -DWITH_DOC=ON -DBUILD_MOOGLI=ON .. && make
    - ctest --output-on-failure
